#!/bin/bash
set -e

# Make disk directory
mkdir -p build/disk

#python starcommand.py -a >build/temp.asm
#python tools/post_process.py <build/temp.asm >starcommand_acme.asm

python3 tools/text_compression.py --input source/sc_text.txt --output build/sc_text.a

function prepare_disk {
    local elk=$1
    local filename=$2
    acme --symbollist build/$2.symbols.txt -r build/$2.report.txt -Delk=$elk -o build/disk/$2 source/starcommand_acme.asm
    sort -o build/symbols.txt build/$2.symbols.txt

    # Find entry point in symbols
    entry_point=$(grep build/$2.symbols.txt -e '.*entry_point' | sed 's/.*\$\([0-9a-f][0-9a-f][0-9a-f][0-9a-f]\).*/\1/')

    # Create INF file
    echo "$.$2     FFFF1E00 FFFF$entry_point" >build/disk/$2.inf

}

# Build !BOOT image
acme -o build/disk/\!BOOT source/boot.asm

# Create INF file for !BOOT
echo "$.!BOOT     FFFF0180 FFFF0180" >build/disk/\!BOOT.inf

prepare_disk 0 STAR
prepare_disk 1 STARELK

# Create new SSD file with the appropriate files
cp templates/EMPTY.ssd STAR2022.ssd
cd build/disk
python3 ../../tools/image.py -d ../../STAR2022.ssd -i !BOOT -i STAR -i STARELK
cd ../..

if [ $USER == "tobynelson" ];
then
    # Open SSD in b2
    osascript -e 'quit app "b2 Debug"'
    sleep 1
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    open -a 'b2 Debug' --args -0 "$DIR/STAR2022.SSD" -b
else
    # Open SSD in BeebEm
    open STAR2022.SSD
fi
